name: Extractor de Canales M3U8

on:
  workflow_dispatch: # Te permite ejecutarlo manualmente cuando quieras desde GitHub
  schedule:
    - cron: '0 */3 * * *' # OPCIONAL: Se ejecuta automáticamente cada 3 horas

jobs:
  run-extractor:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias del script
      run: |
        pip install requests playwright

    - name: Instalar navegadores de Playwright
      run: |
        playwright install chromium --with-deps

    - name: Ejecutar Extractor de Streams
      run: python extraer_streams.py
